sudo: false
language: node_js
node_js:
  - "8"
  - "10"

notifications:
  email: evenchange4@gmail.com

script:
  # - yarn run test
  - yarn run build

cache:
  yarn: true
  directories:
    - node_modules
